version: '3.8'

services:
  app:
    build: .
    container_name: leafscan-app
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:admin123@leafscan-db.cby4m8qqoaqm.ap-southeast-2.rds.amazonaws.com:5432/leafscan_db"
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      PEPPER: ${PEPPER}
    ports:
      - "8080:8080"
    command:
      - sh
      - -c
      - |
        flask db upgrade && gunicorn -b 0.0.0.0:8080 app:app

  seed:
    build: .
    container_name: leafscan-seed
    restart: "no"  # Ensure it doesn't restart
    depends_on:
      - app
    command: ["python3", "seed.py"]